apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregatorservice-common
  namespace: easytrade
data:
  NODE_ENV: "production"
  OFFER_SERVICE: "offerservice:8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregatorservice-1
  namespace: easytrade
data:
  PLATFORM: "dynatestsieger.at"
  STARTER_PACKAGE_PROBABILITY: '0.6'
  LIGHT_PACKAGE_PROBABILITY: '0.3'
  PRO_PACKAGE_PROBABILITY: '0.1'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregatorservice-2
  namespace: easytrade
data:
  PLATFORM: "tradeCom.co.uk"
  STARTER_PACKAGE_PROBABILITY: '0.8'
  LIGHT_PACKAGE_PROBABILITY: '0.2'
  PRO_PACKAGE_PROBABILITY: '0'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregatorservice-3
  namespace: easytrade
data:
  PLATFORM: "CryptoTrading.com"
  FILTER: '["Crypto"]'
  MAXFEE: '0'
  STARTER_PACKAGE_PROBABILITY: '0.5'
  LIGHT_PACKAGE_PROBABILITY: '0.4'
  PRO_PACKAGE_PROBABILITY: '0.1'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregatorservice-4
  namespace: easytrade
data:
  PLATFORM: "CheapTrading.mi"
  MAXFEE: '0'
  STARTER_PACKAGE_PROBABILITY: '1'
  LIGHT_PACKAGE_PROBABILITY: '0'
  PRO_PACKAGE_PROBABILITY: '0'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregatorservice-5
  namespace: easytrade
data:
  PLATFORM: "Stratton-oakmount.com"
  FILTER: '["Shares"]'
  STARTER_PACKAGE_PROBABILITY: '0'
  LIGHT_PACKAGE_PROBABILITY: '0.1'
  PRO_PACKAGE_PROBABILITY: '0.9'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregatorservice
  namespace: easytrade
spec:
  selector:
    matchLabels:
      app: aggregatorservice
  template:
    metadata:
      labels:
        app: aggregatorservice
    spec:
      containers:
      - name: aggregatorservice-1
        image: gcr.io/dynatrace-demoability/easytrade/aggregatorservice:0d8bdc7
        env:
          - name: PLATFORM
            valueFrom:
              configMapKeyRef:
                name: aggregatorservice-1
                key: PLATFORM
          - name: STARTER_PACKAGE_PROBABILITY
            valueFrom:
              configMapKeyRef:
                name: aggregatorservice-1
                key: STARTER_PACKAGE_PROBABILITY
          - name: LIGHT_PACKAGE_PROBABILITY
            valueFrom:
              configMapKeyRef:
                name: aggregatorservice-1
                key: LIGHT_PACKAGE_PROBABILITY
          - name: PRO_PACKAGE_PROBABILITY
            valueFrom:
              configMapKeyRef:
                name: aggregatorservice-1
                key: PRO_PACKAGE_PROBABILITY
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: aggregatorservice-common
                key: NODE_ENV
          - name: OFFER_SERVICE
            valueFrom:
              configMapKeyRef:
                name: aggregatorservice-common
                key: OFFER_SERVICE
        resources: &default_res
          requests:
            cpu: 50m
            memory: 100Mi
      - name: aggregatorservice-2
        image: gcr.io/dynatrace-demoability/easytrade/aggregatorservice:0d8bdc7
        envFrom:
        - configMapRef:
            name: aggregatorservice-common
        - configMapRef:
            name: aggregatorservice-2
        resources: *default_res
      - name: aggregatorservice-3
        image: gcr.io/dynatrace-demoability/easytrade/aggregatorservice:0d8bdc7
        envFrom:
        - configMapRef:
            name: aggregatorservice-common
        - configMapRef:
            name: aggregatorservice-3
        resources: *default_res
      - name: aggregatorservice-4
        image: gcr.io/dynatrace-demoability/easytrade/aggregatorservice:0d8bdc7
        envFrom:
        - configMapRef:
            name: aggregatorservice-common
        - configMapRef:
            name: aggregatorservice-4
        resources: *default_res
      - name: aggregatorservice-5
        image: gcr.io/dynatrace-demoability/easytrade/aggregatorservice:0d8bdc7
        envFrom:
        - configMapRef:
            name: aggregatorservice-common
        - configMapRef:
            name: aggregatorservice-5
        resources: *default_res
