apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculationservice
  namespace: easytrade
spec:
  selector:
    matchLabels:
      app: calculationservice
  template:
    metadata:
      labels:
        app: calculationservice
    spec:
      containers:
      - name: calculationservice
        image: gcr.io/dynatrace-demoability/easytrade/calculationservice:0d8bdc7
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
