apiVersion: apps/v1
kind: Deployment
metadata:
  name: pluginservice
  namespace: easytrade
spec:
  selector:
    matchLabels:
      app: pluginservice
  template:
    metadata:
      labels:
        app: pluginservice
    spec:
      containers:
      - name: pluginservice
        image: gcr.io/dynatrace-demoability/easytrade/pluginservice:0d8bdc7
        ports:
        - containerPort: 8080
        env:
        - name: OFFER_SERVICE__PORT
          value: '8080'
        - name: OFFER_SERVICE__DOMAIN
          value: offerservice
        - name: MANAGER__DOMAIN
          value: manager
        - name: MANAGER__PORT
          value: '80'
        resources:
          requests:
            cpu: 150m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pluginservice
  namespace: easytrade
spec:
  type: ClusterIP
  selector:
    app: pluginservice
  ports:
  - name: http
    port: 8080
    targetPort: 8080
